version: "3.8"

services:
  # MinIO S3-compatible storage
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - sync-network

  # S3 to GDrive Sync service
  sync:
    build: .
    container_name: gdrive-s3-sync
    restart: unless-stopped
    depends_on:
      - minio
    env_file:
      - .env
    volumes:
      - ./credentials:/app/credentials:ro
      - ./logs:/app/logs
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-gdrive-sync}
      - S3_ENDPOINT_URL=http://minio:9000 # Use MinIO container
      - GDRIVE_FOLDER_ID=${GDRIVE_FOLDER_ID}
      - GDRIVE_CREDENTIALS_PATH=/app/credentials/credentials.json
      - SYNC_INTERVAL_SECONDS=${SYNC_INTERVAL_SECONDS:-300}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - sync-network

volumes:
  minio-data:
    driver: local

networks:
  sync-network:
    driver: bridge
